### ISSUE TITLE
[question] is this not usable anymore?

### ISSUE THREAD

**Issue by moebiussurfing** [rystylee/ofxVFX-old#1]
hey @rystylee , thanks for sharing.
I am getting this error in macOS/OF 0.10...

`/of_v0.10.1_osx_release/libs/openFrameworks/utils/ofConstants.h:425:51: Non-constant-expression cannot be narrowed from type 'int' to 'U' (aka 'float') in initializer list`

I am just curious to check the effects, if you think it worth... but why do you tagged as old?

**Comment by rystylee** [comment]
I think that error comes from using C++11. Is it possible to try compiling with C++14?

or please try to change

https://github.com/rystylee/ofxVFX-old/blob/35ca788355b8cbba5f7e2dd19ed6ad484a377b71/src/VFX.hpp#L26


to
```
std::unique_ptr<T> pass(new T());
mRenderPasses.emplace_back(std::move(pass));
```

I name this repository "old" simply because I am working on a different representation. Sorry for the confusion...

**Comment by moebiussurfing** [comment]
Thanks a lot @rystylee for you tip!
It's working here in macOS High Sierra changing from c++11 to c++14 on Xcode like this:
![Screen Shot 2019-12-19 at 21 05 33](https://user-images.githubusercontent.com/2106149/71219338-808d9f00-22a3-11ea-9cc8-29e2490b7af2.png)
I have similar errors in some other OF addons/projects that seem are made in Windows.
That tip can solve them too. I was messing around with Clang//LLVM versions checking..
Thanks for sharing
